#!/bin/zsh

#tor
if ps -ax | grep -w tor | grep -v grep > /dev/null 2>&1;then
   unset http_proxy
   unset https_proxy
   unset HTTP_PROXY
   unset HTTPS_PROXY
   socks="--socks5 127.0.0.1:9050"
fi

dir=~/Music/miku
file=$dir/url.txt
mkdir -p $dir

#help
#curl -s https://gist.githubusercontent.com/azu/239541/raw/NicoMylistDom.js

case $# in
    0)
        numb=""
        #url=http://www.nicovideo.jp/mylist/${numb}
        url=`cat ~/dotfiles/Documents/nicourl.txt | peco`
    ;;
    1)
        if echo $1 | grep http > /dev/null 2>&1 ; then 
            url=$1
            #url=${title##*/}
        else
            url=http://www.nicovideo.jp/mylist/${1}
        fi
    ;;
esac

cd $dir

surl=`curl -sL $socks $url | sed -e 's/"watch_id":"/http:\/\/www.nicovideo.jp\/watch\//g' | perl -pe 's/"}/\n/g' | perl -pe 's/,/\n/g'`
url=`echo $surl | grep "http://www.nicovideo.jp/watch/" | tac`
stime=`echo $surl | grep update_time | grep "}" | cut -d : -f2 | cut -b -10 | tac`

val=`echo $url | wc -l | tr -d ' '`

if [ -f $file ];then
    rm $file
fi

if [ $val -le 10 ];then

for ((i=1;i<=$val;i++))
do
    nico=`echo $url | awk "NR==$i"`
    ntime=`echo $stime | awk "NR==$i"`
    case $OSTYPE in
        linux*)
            #otime=`date --date "@${ntime}"`
            otime=`date --date @$ntime +"%y/%m/%d"`
            ;;
        darwin*)
            otime=`date -r $ntime`
            ;;
    esac
    otitle=`curl -sL $socks  -f $nico | grep -o -E '<title>.+</title>' | sed -e 's#<title>##g' -e 's#</title>##g'`
    echo $otime:$otitle,$nico
done | sort -Mr | peco | cut -d , -f 2- > $file

else
    echo "$url" | peco > $file
fi


#tor {{{
if ps -ax | grep -w tor | grep -v grep > /dev/null 2>&1;then
    if which proxychains > /dev/null 2>&1;then
        proxychains youtube-dl `cat $file`
    elif which proxychains4 > /dev/null 2>&1;then
        proxychains4 youtube-dl `cat $file`
    else
        youtube-dl -w -a $file
    fi
else
    youtube-dl -w -a $file
fi
#}}}

##youtube-dl --restrict-filenames -w -a $file
#
rm $file
echo $http_proxy
