#!/bin/zsh

bas=`cat << EOF | peco | tr -d ' '
mp4 -> mp3
flv -> mp3
swf -> mp3
mp3 -> wav
flv -> wav
mov -> gif
jpg -> png
jpeg -> png
bmp -> png
wav -> 2xmp3
EOF` > /dev/null 2>&1

inp=`echo $bas | cut -d '-' -f 1`
oup=`echo $bas | cut -d '>' -f 2`

case $inp in

    swf)
        for i in *.${inp}; do swfextract -m $i -o ${i%.swf}.mp3; done
    ;;

    mov)
        for i in *.${inp}; do ffmpeg -i *.mov -r 8 %04d.png && gm convert *.png ${i%.*}.gif && rm *.png; done
    ;;

    jpg)
        mogrify -format png -quality 100 *.jpg
    ;;

    jpeg)
        mogrify -format png -quality 100 *.jpeg
    ;;

    bmp)
        mogrify -format png -quality 100 *.bmp
    ;;

    wav)
        ffmpeg -i *.wav -af "atempo=1.3,atempo=1.3" -ab 302k 2x.mp3
    ;;
    *)
        for i in *.${inp}; do ffmpeg -i $i -vn ${i%.*}.${oup}; done
    ;;

esac
